### PR TITLE
Migrate to Rust 2018 edition

### PR DESCRIPTION
**Pull request by frol**
It is just the first step.

I want to migrate wampire to Rust 1.39 async/await. To do that, I am going to replace `eventual` with `tokio` (0.2 alpha)  and `ws` with [`tungstenite`](https://github.com/snapview/tungstenite-rs) & [`tokio-tungstenite`](https://github.com/snapview/tokio-tungstenite) ([async/await support is currently in PR](https://github.com/snapview/tokio-tungstenite/pull/68)).

### CODE REVIEW

**Comment by dudochkin-victor** [comment]
but I think you should be more patient in order to be compatible with systems that support a stable version of the language.

**Comment by frol** [comment]
Async/await will land to stable in 2 days :)

Also, we can do alpha releases and follow Tokio releases.

**Comment by dudochkin-victor** [comment]
I am telling you about accepting the release of a programming language in operating systems. Thank you anyway. Keep patience.. maybe branch and add you to this repo?

**Comment by frol** [comment]
I am not rushing a release. I am completely fine with a separate branch or non-released master. I am starting a new project and after spending another round of searching for a good foundation for inter-service communication I came back to WAMP-proto and I am in love with Rust and async/await, so here I am. I am going to work through the migration in my fork and time will show whether I will succeed with that and then we will be in a better position to discuss the organizational questions :)

**Comment by dudochkin-victor** [comment]
Let me tell u one thing.. 
Вебню на сервере нужно писать на голанге, шкурки нужно писать или на вуе или на дарте, серверные вещи нужно писать на расте..
Потому что Гугл пишет всю серверную вебню на голанге, а шкурки у них на дарте. Так вот Раст он - тогда когда го не хватает.

**Comment by dudochkin-victor** [comment]
А если хочешь реально занаться вампом... то там спека до конца не реализована... читай спецификацию, и реализовывай ее..)))

**Pull request merged**
